import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboad ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-full gap-4 bg-slate-200">

        <Sidebar/>
        <div className="flex flex-col w-full p-4   ">
        {children}
        </div>
        </div>
        </body>
       
    </html>
  );
}
