const CustomerData = [
    {
      id: 1,
      customer_name: "Jane Copper",
      company: "Microsoft",
      phoneno: "(255) 555-0118",
      email: "jane@microsoft.com",
      country: "United States",
    },
    {
      id: 2,
      customer_name: "John Doe",
      company: "Google",
      phoneno: "(312) 555-0199",
      email: "john@google.com",
      country: "Canada",
    },
    {
      id: 3,
      customer_name: "Alice Smith",
      company: "Apple",
      phoneno: "(415) 555-0167",
      email: "alice@apple.com",
      country: "Australia",
    },
    {
      id: 4,
      customer_name: "Bob Johnson",
      company: "Amazon",
      phoneno: "(206) 555-0149",
      email: "bob@amazon.com",
      country: "Germany",
    },
    {
      id: 5,
      customer_name: "Emily Brown",
      company: "Facebook",
      phoneno: "(650) 555-0135",
      email: "emily@facebook.com",
      country: "France",
    },
    {
      id: 6,
      customer_name: "Michael Davis",
      company: "Tesla",
      phoneno: "(510) 555-0146",
      email: "michael@tesla.com",
      country: "Japan",
    },
    {
      id: 7,
      customer_name: "Sophia Wilson",
      company: "Netflix",
      phoneno: "(408) 555-0155",
      email: "sophia@netflix.com",
      country: "Brazil",
    },
    {
      id: 8,
      customer_name: "William Martinez",
      company: "Uber",
      phoneno: "(415) 555-0142",
      email: "william@uber.com",
      country: "Mexico",
    },
    {
      id: 9,
      customer_name: "Olivia Garcia",
      company: "Twitter",
      phoneno: "(415) 555-0178",
      email: "olivia@twitter.com",
      country: "Spain",
    },
    {
      id: 10,
      customer_name: "James Rodriguez",
      company: "Spotify",
      phoneno: "(917) 555-0198",
      email: "james@spotify.com",
      country: "Italy",
    },
    {
      id: 11,
      customer_name: "Emma Moore",
      company: "Salesforce",
      phoneno: "(415) 555-0126",
      email: "emma@salesforce.com",
      country: "India",
    },
    {
      id: 12,
      customer_name: "Alexander Thompson",
      company: "Adobe",
      phoneno: "(408) 555-0187",
      email: "alexander@adobe.com",
      country: "South Africa",
    },
    {
      id: 13,
      customer_name: "Charlotte Clark",
      company: "LinkedIn",
      phoneno: "(650) 555-0115",
      email: "charlotte@linkedin.com",
      country: "United Kingdom",
    },
    {
      id: 14,
      customer_name: "Ethan Lewis",
      company: "Pinterest",
      phoneno: "(650) 555-0179",
      email: "ethan@pinterest.com",
      country: "Russia",
    },
    {
      id: 15,
      customer_name: "Isabella Lee",
      company: "PayPal",
      phoneno: "(408) 555-0139",
      email: "isabella@paypal.com",
      country: "China",
    },
    {
      id: 16,
      customer_name: "Mason Walker",
      company: "Snapchat",
      phoneno: "(310) 555-0180",
      email: "mason@snapchat.com",
      country: "South Korea",
    },
    {
      id: 17,
      customer_name: "Amelia Hall",
      company: "Reddit",
      phoneno: "(415) 555-0148",
      email: "amelia@reddit.com",
      country: "Argentina",
    },
    {
      id: 18,
      customer_name: "Logan Allen",
      company: "Dropbox",
      phoneno: "(415) 555-0192",
      email: "logan@dropbox.com",
      country: "Netherlands",
    },
    {
      id: 19,
      customer_name: "Ava Young",
      company: "Airbnb",
      phoneno: "(650) 555-0125",
      email: "ava@airbnb.com",
      country: "Singapore",
    },
    {
      id: 20,
      customer_name: "Liam Green",
      company: "Lyft",
      phoneno: "(415) 555-0152",
      email: "liam@lyft.com",
      country: "Sweden",
    },
    {
      id: 21,
      customer_name: "Aria Scott",
      company: "Square",
      phoneno: "(415) 555-0185",
      email: "aria@square.com",
      country: "Switzerland",
    },
    {
      id: 22,
      customer_name: "Noah Baker",
      company: "Shopify",
      phoneno: "(613) 555-0169",
      email: "noah@shopify.com",
      country: "New Zealand",
    },
    {
      id: 23,
      customer_name: "Grace Ward",
      company: "Zendesk",
      phoneno: "(415) 555-0122",
      email: "grace@zendesk.com",
      country: "Egypt",
    },
    {
      id: 24,
      customer_name: "Benjamin Morris",
      company: "Zoom",
      phoneno: "(408) 555-0177",
      email: "benjamin@zoom.com",
      country: "Turkey",
    },
    {
      id: 25,
      customer_name: "Ella Rivera",
      company: "DoorDash",
      phoneno: "(650) 555-0158",
      email: "ella@doordash.com",
      country: "Saudi Arabia",
    },
    {
      id: 26,
      customer_name: "Jackson Cook",
      company: "Stripe",
      phoneno: "(415) 555-0147",
      email: "jackson@stripe.com",
      country: "Thailand",
    },
    {
      id: 27,
      customer_name: "Stella Parker",
      company: "GitHub",
      phoneno: "(415) 555-0136",
      email: "stella@github.com",
      country: "Vietnam",
    }
    
]
export default CustomerData;
  